### ISSUE TITLE
Cycle with time series

### ISSUE THREAD

**Issue by amoussoubaruch** [umbertogriffo/Predictive-Maintenance-using-LSTM#1]
Hi man,

You have very good explain how to use neuronal network for predictive maintenance case. 
So i have a question about data. How can you create cycle feature in your dataset (train)? 

Thanks

**Comment by umbertogriffo** [comment]
Hi @amoussoubaruch,
Thank you very much!
Actually I didn't create the cycle feature.
The feature already existed in the original dataset that you can find [here](https://ti.arc.nasa.gov/tech/dash/groups/pcoe/prognostic-data-repository/#turbofan)

**Comment by amoussoubaruch** [comment]
Good received. I will check it
Many Thanks
