### ISSUE TITLE
target==s21 ?

### ISSUE THREAD

**Issue by linrio** [umbertogriffo/Predictive-Maintenance-using-LSTM#2]
I know that the "cycle" is the time unit. And 21 sensor readings is the features.  Now I have a question:

if the ground truth data is not the "cycle", **the ground truth data is the sensor of s21**(for example). How to utilize LSTM  to predict the ground truth data(s21)? If I want to predict the values of s21 from 23 cycle to 30 cycle(sequence time series), how to predict? 

such as:
![image](https://user-images.githubusercontent.com/16930748/39314492-f026efa6-49a6-11e8-8882-185c46f6c8e7.png)

Tks!

**Comment by linrio** [comment]
Now I think that we can utilize the one-hot encoder ?

**Comment by dmfolgado** [comment]
You only need to change the target variable. You have to ensure that for each `X_train` window, the `y_test` which is associate is not the RUL but the next respective value for **s21**.

**Comment by umbertogriffo** [comment]
@dmfolgado it's correct, thank you for having answered for me!
