### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by bi-j-o5777** [umbertogriffo/Predictive-Maintenance-using-LSTM#6]
HI 
im a student from a collage in Norway and im approching pyton  and machine learing but my teacher isn't so good, so i try to learn it by myself (i'm a super beginner) and i have some questions:
1)in the training data we have simulated sensor data and when the engine breaks so we use it for the LSTM learning right?
2) i understood that we use traning data to see if our lstm works but why we have alredy RUL of testing data?
3) i dont know what represents the two blue and green graphs (one results in regression model and in one in binary classification) with actual data compared to predicted data
thank you and happy holidays and sorry if some questions are stupid
tom

**Comment by kibetanui** [comment]
2. To compare the actual RUL VS RUL predicted by our model

**Comment by bi-j-o5777** [comment]
thanks for your answer, i thought that too but for example engine 1 (in row 1) has not 70 cycles left, it has 112 . i think i don't read the graph in the right way the graph
