### ISSUE TITLE
About the model

### ISSUE THREAD

**Issue by dudugrace** [umbertogriffo/Predictive-Maintenance-using-LSTM#7]
Hi, man

You have made a pretty predictive model with LSTM. I am a Ph.D student and I want to know if your model has been published as a journal paper. If it has been published as a journal paper, I wish you could tell me the DOI of the paper or the information about the paper. Thank you very much!!

**Comment by wilson-xiong** [comment]
Hi, bro
This is not my work. I just collect it. You can find the related paper about predictive model with LSTM by the key work.



***@***.***
 
From: dudugrace
Date: 2023-02-02 14:11
To: umbertogriffo/Predictive-Maintenance-using-LSTM
CC: Subscribed
Subject: [umbertogriffo/Predictive-Maintenance-using-LSTM] About the model (Issue #7)
Hi, man
You have made a pretty predictive model with LSTM. I am a Ph.D student and I want to know if your model has been published as a journal paper. If it has been published as a journal paper, I wish you could tell me the DOI of the paper or the information about the paper. Thank you very much!!

**Comment by dudugrace** [comment]
Ok, thank you very much.
